# teacher_texts.py

TEACHER_TEXTS = [
    # =========================================================
    # A1 (10)
    # =========================================================
    {
        "id": "a1_greetings_01",
        "title": "Saluer quelqu’un",
        "level": "A1",
        "unit": "Introductions",
        "theme": "Greetings",
        "focus": "basic vowels, greeting formula, smooth rhythm",
        "grammar_focus": "present tense, polite formulas",
        "skills": ["reading aloud", "greetings", "connected speech"],
        "target_words": ["bonjour", "comment", "allez-vous", "aujourd'hui"],
        "liaison_targets": ["comment allez-vous"],
        "teacher_tip": "Encourage learners not to pause between common greeting words.",
        "text": "Bonjour, comment allez-vous aujourd'hui ?"
    },
    {
        "id": "a1_intro_01",
        "title": "Se présenter",
        "level": "A1",
        "unit": "Introductions",
        "theme": "Personal information",
        "focus": "clear vowels, basic sentence rhythm",
        "grammar_focus": "je m'appelle, je suis",
        "skills": ["reading aloud", "self-introduction"],
        "target_words": ["appelle", "étudiante", "Marie"],
        "liaison_targets": [],
        "teacher_tip": "Model each chunk first, then have students repeat the full sentence.",
        "text": "Je m'appelle Marie et je suis étudiante."
    },
    {
        "id": "a1_age_01",
        "title": "Dire son âge",
        "level": "A1",
        "unit": "Personal information",
        "theme": "Age and numbers",
        "focus": "numbers, nasal vowels",
        "grammar_focus": "j'ai, il/elle a",
        "skills": ["reading aloud", "numbers", "personal information"],
        "target_words": ["vingt", "ans", "dix-huit"],
        "liaison_targets": ["vingt ans"],
        "teacher_tip": "Pay attention to number pronunciation and the nasal vowel in 'ans'.",
        "text": "J'ai vingt ans et mon frère a dix-huit ans."
    },
    {
        "id": "a1_family_01",
        "title": "Ma famille",
        "level": "A1",
        "unit": "Family",
        "theme": "Family",
        "focus": "simple rhythm, contrast of singular and plural",
        "grammar_focus": "articles, possessives",
        "skills": ["reading aloud", "family vocabulary"],
        "target_words": ["frère", "sœur", "cousins"],
        "liaison_targets": [],
        "teacher_tip": "Have learners mark stress lightly on family nouns.",
        "text": "J'ai un frère, une sœur et deux cousins."
    },
    {
        "id": "a1_bakery_01",
        "title": "À la boulangerie",
        "level": "A1",
        "unit": "Food and shopping",
        "theme": "Shopping",
        "focus": "polite requests, nasal vowels",
        "grammar_focus": "je voudrais",
        "skills": ["reading aloud", "shopping", "polite interaction"],
        "target_words": ["voudrais", "baguette", "plaît"],
        "liaison_targets": [],
        "teacher_tip": "Encourage smooth rhythm in the phrase 's'il vous plaît'.",
        "text": "Bonjour monsieur, je voudrais une baguette, s'il vous plaît."
    },
    {
        "id": "a1_classroom_01",
        "title": "Dans la classe",
        "level": "A1",
        "unit": "School life",
        "theme": "Classroom",
        "focus": "imperatives, clear articulation",
        "grammar_focus": "ouvrez, regardez",
        "skills": ["reading aloud", "classroom language"],
        "target_words": ["ouvrez", "livre", "page"],
        "liaison_targets": [],
        "teacher_tip": "Keep the command tone friendly but clear.",
        "text": "Ouvrez le livre à la page dix, s'il vous plaît."
    },
    {
        "id": "a1_weekdays_01",
        "title": "Les jours de la semaine",
        "level": "A1",
        "unit": "Time",
        "theme": "Calendar",
        "focus": "rhythm, repeated stress pattern",
        "grammar_focus": "sequencing vocabulary",
        "skills": ["reading aloud", "time vocabulary"],
        "target_words": ["lundi", "mercredi", "dimanche"],
        "liaison_targets": [],
        "teacher_tip": "Use tapping to reinforce syllable rhythm.",
        "text": "Lundi, mardi, mercredi, jeudi, vendredi, samedi et dimanche."
    },
    {
        "id": "a1_home_01",
        "title": "Ma maison",
        "level": "A1",
        "unit": "Home",
        "theme": "House and rooms",
        "focus": "simple descriptive phrasing",
        "grammar_focus": "il y a",
        "skills": ["reading aloud", "describing places"],
        "target_words": ["maison", "cuisine", "chambres"],
        "liaison_targets": [],
        "teacher_tip": "Ask learners to pause only at natural phrase boundaries.",
        "text": "Dans ma maison, il y a une cuisine et deux chambres."
    },
    {
        "id": "a1_restaurant_01",
        "title": "Au restaurant",
        "level": "A1",
        "unit": "Food and shopping",
        "theme": "Restaurant",
        "focus": "food vocabulary, vowel clarity",
        "grammar_focus": "je prends",
        "skills": ["reading aloud", "ordering food"],
        "target_words": ["prends", "poisson", "orange"],
        "liaison_targets": [],
        "teacher_tip": "Practice food groups as chunks, not isolated words.",
        "text": "Je prends du riz, du poisson et un jus d'orange."
    },
    {
        "id": "a1_weather_01",
        "title": "Parler de la météo",
        "level": "A1",
        "unit": "Daily life",
        "theme": "Weather",
        "focus": "open vowels, everyday statements",
        "grammar_focus": "il fait, il y a",
        "skills": ["reading aloud", "weather vocabulary"],
        "target_words": ["aujourd'hui", "soleil", "beau"],
        "liaison_targets": [],
        "teacher_tip": "Keep a calm rhythm and clear final vowels.",
        "text": "Aujourd'hui, il fait beau et il y a du soleil."
    },

    # =========================================================
    # A2 (10)
    # =========================================================
    {
        "id": "a2_routine_01",
        "title": "Ma routine du matin",
        "level": "A2",
        "unit": "Daily life",
        "theme": "Routine",
        "focus": "enchaînement, time expressions",
        "grammar_focus": "reflexive verbs, present tense",
        "skills": ["reading aloud", "daily routine", "connected speech"],
        "target_words": ["lève", "heures", "petit-déjeuner"],
        "liaison_targets": ["six heures"],
        "teacher_tip": "Encourage learners to keep time expressions fluid.",
        "text": "Le matin, je me lève à six heures et je prends mon petit-déjeuner."
    },
    {
        "id": "a2_market_01",
        "title": "Au marché",
        "level": "A2",
        "unit": "Food and shopping",
        "theme": "Shopping",
        "focus": "connected groups, food vocabulary",
        "grammar_focus": "partitive articles",
        "skills": ["reading aloud", "shopping vocabulary"],
        "target_words": ["marché", "acheter", "fromage"],
        "liaison_targets": ["des oranges"],
        "teacher_tip": "Have learners group article + noun together when reading.",
        "text": "Je vais au marché pour acheter des oranges, du pain et du fromage."
    },
    {
        "id": "a2_directions_01",
        "title": "Demander son chemin",
        "level": "A2",
        "unit": "Travel and directions",
        "theme": "Directions",
        "focus": "question intonation, polite forms",
        "grammar_focus": "où se trouve",
        "skills": ["reading aloud", "asking for directions"],
        "target_words": ["excusez-moi", "trouve", "gare"],
        "liaison_targets": [],
        "teacher_tip": "Model rising intonation for polite questions.",
        "text": "Excusez-moi, monsieur, où se trouve la gare, s'il vous plaît ?"
    },
    {
        "id": "a2_schedule_01",
        "title": "Mon emploi du temps",
        "level": "A2",
        "unit": "School life",
        "theme": "Schedule",
        "focus": "linked phrasing, days and times",
        "grammar_focus": "avoir cours, expressions of time",
        "skills": ["reading aloud", "talking about schedules"],
        "target_words": ["emploi", "temps", "histoire"],
        "liaison_targets": [],
        "teacher_tip": "Encourage phrase grouping around time expressions.",
        "text": "Le lundi, j'ai cours de français le matin et d'histoire l'après-midi."
    },
    {
        "id": "a2_transport_01",
        "title": "Prendre le bus",
        "level": "A2",
        "unit": "Travel and directions",
        "theme": "Transport",
        "focus": "rhythm in short narrative sentences",
        "grammar_focus": "present tense, purpose with pour",
        "skills": ["reading aloud", "transport vocabulary"],
        "target_words": ["prends", "université", "huit"],
        "liaison_targets": [],
        "teacher_tip": "Keep the sentence moving naturally without choppy pauses.",
        "text": "Je prends le bus à huit heures pour aller à l'université."
    },
    {
        "id": "a2_hobbies_01",
        "title": "Parler de ses loisirs",
        "level": "A2",
        "unit": "Free time",
        "theme": "Hobbies",
        "focus": "list intonation, rhythm",
        "grammar_focus": "aimer + infinitive",
        "skills": ["reading aloud", "free-time activities"],
        "target_words": ["week-end", "écouter", "football"],
        "liaison_targets": [],
        "teacher_tip": "Practice the sentence as a list with natural rises and falls.",
        "text": "Le week-end, j'aime lire, écouter de la musique et jouer au football."
    },
    {
        "id": "a2_city_01",
        "title": "Décrire une ville",
        "level": "A2",
        "unit": "Places",
        "theme": "City life",
        "focus": "adjective sequences, smooth flow",
        "grammar_focus": "être + adjectives",
        "skills": ["reading aloud", "describing places"],
        "target_words": ["calme", "propre", "agréable"],
        "liaison_targets": [],
        "teacher_tip": "Encourage learners to keep adjective sequences connected.",
        "text": "Ma ville est calme, propre et très agréable à visiter."
    },
    {
        "id": "a2_vacation_01",
        "title": "Raconter ses vacances",
        "level": "A2",
        "unit": "Travel",
        "theme": "Vacations",
        "focus": "past reference, phrase grouping",
        "grammar_focus": "passé composé with être",
        "skills": ["reading aloud", "talking about past events"],
        "target_words": ["année", "dernière", "famille"],
        "liaison_targets": [],
        "teacher_tip": "Use chunking to support longer past-tense sentences.",
        "text": "L'année dernière, je suis allé à Dakar avec ma famille."
    },
    {
        "id": "a2_health_01",
        "title": "À la pharmacie",
        "level": "A2",
        "unit": "Health",
        "theme": "Health",
        "focus": "nasal vowels, clear requests",
        "grammar_focus": "je cherche",
        "skills": ["reading aloud", "health vocabulary"],
        "target_words": ["médicament", "contre", "tête"],
        "liaison_targets": [],
        "teacher_tip": "Practice the request slowly first, then naturally.",
        "text": "Bonjour, je cherche un médicament contre le mal de tête."
    },
    {
        "id": "a2_weather_02",
        "title": "Prévoir le temps",
        "level": "A2",
        "unit": "Daily life",
        "theme": "Weather",
        "focus": "intonation in prediction",
        "grammar_focus": "future proche",
        "skills": ["reading aloud", "weather description"],
        "target_words": ["demain", "pleuvoir", "température"],
        "liaison_targets": [],
        "teacher_tip": "Have learners distinguish today's weather from tomorrow's forecast.",
        "text": "Demain, il va pleuvoir et la température va baisser dans la soirée."
    },

    # =========================================================
    # B1 (10)
    # =========================================================
    {
        "id": "b1_travel_01",
        "title": "Voyager en train",
        "level": "B1",
        "unit": "Travel",
        "theme": "Transport",
        "focus": "rhythm, longer phrasing",
        "grammar_focus": "future tense",
        "skills": ["reading aloud", "transport vocabulary"],
        "target_words": ["partira", "heures", "centrale"],
        "liaison_targets": ["huit heures"],
        "teacher_tip": "Help learners group the sentence into meaningful thought units.",
        "text": "Le train partira à huit heures du matin de la gare centrale."
    },
    {
        "id": "b1_opinion_01",
        "title": "Donner son opinion",
        "level": "B1",
        "unit": "Expressing opinions",
        "theme": "Environment",
        "focus": "sentence melody, contrastive stress",
        "grammar_focus": "il est important de",
        "skills": ["reading aloud", "giving opinions"],
        "target_words": ["important", "protéger", "environnement"],
        "liaison_targets": ["il est"],
        "teacher_tip": "Model how emphasis changes the tone of the sentence.",
        "text": "À mon avis, il est important de protéger l'environnement dès maintenant."
    },
    {
        "id": "b1_biography_01",
        "title": "Parler de son parcours",
        "level": "B1",
        "unit": "Biography",
        "theme": "Education",
        "focus": "connected narration, longer sentences",
        "grammar_focus": "après + noun, infinitive structures",
        "skills": ["reading aloud", "narrating a path"],
        "target_words": ["études", "secondaires", "formation"],
        "liaison_targets": [],
        "teacher_tip": "Use commas to guide breathing and phrase grouping.",
        "text": "Après mes études secondaires, j'ai décidé de poursuivre une formation en langues."
    },
    {
        "id": "b1_jobs_01",
        "title": "Choisir un métier",
        "level": "B1",
        "unit": "Work",
        "theme": "Career",
        "focus": "longer groups, lexical clarity",
        "grammar_focus": "vouloir devenir, parce que",
        "skills": ["reading aloud", "career vocabulary"],
        "target_words": ["devenir", "enseignant", "connaissances"],
        "liaison_targets": [],
        "teacher_tip": "Encourage learners to stress the key noun in each phrase group.",
        "text": "Je voudrais devenir enseignant parce que j'aime transmettre mes connaissances."
    },
    {
        "id": "b1_social_media_01",
        "title": "Les réseaux sociaux",
        "level": "B1",
        "unit": "Technology",
        "theme": "Media",
        "focus": "contrastive phrasing, linked discourse",
        "grammar_focus": "mais, opposition structures",
        "skills": ["reading aloud", "technology vocabulary"],
        "target_words": ["réseaux", "facilitent", "distraction"],
        "liaison_targets": [],
        "teacher_tip": "Use intonation to mark the contrast introduced by 'mais'.",
        "text": "Les réseaux sociaux facilitent la communication, mais ils peuvent aussi créer de la distraction."
    },
    {
        "id": "b1_university_01",
        "title": "La vie universitaire",
        "level": "B1",
        "unit": "Education",
        "theme": "University life",
        "focus": "prosodic grouping, formal rhythm",
        "grammar_focus": "devoir + infinitive",
        "skills": ["reading aloud", "academic life"],
        "target_words": ["université", "organiser", "efficacement"],
        "liaison_targets": [],
        "teacher_tip": "Encourage balanced pacing for long multisyllabic words.",
        "text": "À l'université, les étudiants doivent apprendre à organiser leur temps efficacement."
    },
    {
        "id": "b1_health_01",
        "title": "L'alimentation saine",
        "level": "B1",
        "unit": "Health",
        "theme": "Health",
        "focus": "argument rhythm, clear advice",
        "grammar_focus": "il faut + infinitive",
        "skills": ["reading aloud", "health advice"],
        "target_words": ["équilibré", "exercice", "régulièrement"],
        "liaison_targets": [],
        "teacher_tip": "Keep the advice pattern steady and confident.",
        "text": "Pour rester en bonne santé, il faut manger équilibré et faire de l'exercice régulièrement."
    },
    {
        "id": "b1_memory_01",
        "title": "Un souvenir d’enfance",
        "level": "B1",
        "unit": "Past experiences",
        "theme": "Memory",
        "focus": "past narrative flow",
        "grammar_focus": "imparfait, habitual past",
        "skills": ["reading aloud", "storytelling"],
        "target_words": ["enfant", "passais", "grands-parents"],
        "liaison_targets": [],
        "teacher_tip": "Have learners read the sentence as a memory, not a list of words.",
        "text": "Quand j'étais enfant, je passais souvent mes vacances chez mes grands-parents."
    },
    {
        "id": "b1_abroad_01",
        "title": "Habiter à l’étranger",
        "level": "B1",
        "unit": "Mobility",
        "theme": "Migration",
        "focus": "intonation in explanation",
        "grammar_focus": "permettre de + infinitive",
        "skills": ["reading aloud", "intercultural reflection"],
        "target_words": ["étranger", "découvrir", "penser"],
        "liaison_targets": [],
        "teacher_tip": "Encourage learners to make the sentence sound reflective and fluid.",
        "text": "Vivre à l'étranger permet de découvrir d'autres cultures et d'autres façons de penser."
    },
    {
        "id": "b1_languages_01",
        "title": "L’importance des langues",
        "level": "B1",
        "unit": "Languages",
        "theme": "Language learning",
        "focus": "formal register, connected speech",
        "grammar_focus": "present tense, abstract noun phrases",
        "skills": ["reading aloud", "language advocacy"],
        "target_words": ["plusieurs", "professionnel", "personnel"],
        "liaison_targets": [],
        "teacher_tip": "Model the sentence in two large meaning groups.",
        "text": "Apprendre plusieurs langues ouvre des portes dans le monde professionnel et personnel."
    },

    # =========================================================
    # B2 (10)
    # =========================================================
    {
        "id": "b2_work_01",
        "title": "Le travail moderne",
        "level": "B2",
        "unit": "Society and work",
        "theme": "Society",
        "focus": "formal phrasing, fluency",
        "grammar_focus": "complex noun phrases",
        "skills": ["reading aloud", "formal discourse"],
        "target_words": ["télétravail", "transforme", "professionnelles"],
        "liaison_targets": [],
        "teacher_tip": "Encourage slower pacing for long formal words.",
        "text": "Le télétravail transforme profondément les habitudes professionnelles dans de nombreux pays."
    },
    {
        "id": "b2_education_01",
        "title": "Débat sur l’éducation",
        "level": "B2",
        "unit": "Education and society",
        "theme": "Education",
        "focus": "prosody, argumentation",
        "grammar_focus": "impersonal structures",
        "skills": ["reading aloud", "argumentation"],
        "target_words": ["essentiel", "investir", "publique"],
        "liaison_targets": [],
        "teacher_tip": "Use a firm tone to reflect argumentative force.",
        "text": "Il est essentiel d'investir davantage dans l'éducation publique."
    },
    {
        "id": "b2_cities_01",
        "title": "Les défis urbains",
        "level": "B2",
        "unit": "Cities and society",
        "theme": "Urban life",
        "focus": "complex noun groups, phrase length",
        "grammar_focus": "abstract nominal structures",
        "skills": ["reading aloud", "social analysis"],
        "target_words": ["croissance", "logement", "sécurité"],
        "liaison_targets": [],
        "teacher_tip": "Encourage learners to mark commas mentally while reading.",
        "text": "La croissance urbaine rapide pose des défis majeurs en matière de logement, de transport et de sécurité."
    },
    {
        "id": "b2_digital_01",
        "title": "La place du numérique",
        "level": "B2",
        "unit": "Technology",
        "theme": "Digital life",
        "focus": "contrast and emphasis",
        "grammar_focus": "mais, opposition, impersonal forms",
        "skills": ["reading aloud", "formal explanation"],
        "target_words": ["immenses", "opportunités", "éthiques"],
        "liaison_targets": [],
        "teacher_tip": "Contrast the positive and negative parts of the sentence clearly.",
        "text": "Le numérique offre d'immenses opportunités, mais il soulève également des questions éthiques importantes."
    },
    {
        "id": "b2_media_01",
        "title": "Les médias aujourd’hui",
        "level": "B2",
        "unit": "Media and communication",
        "theme": "Media",
        "focus": "formal fluency, phrase control",
        "grammar_focus": "present tense in analysis",
        "skills": ["reading aloud", "media analysis"],
        "target_words": ["influencent", "opinion", "crise"],
        "liaison_targets": [],
        "teacher_tip": "Encourage steady pace and clear consonants in key nouns.",
        "text": "Les médias influencent fortement l'opinion publique, surtout en période de crise politique."
    },
    {
        "id": "b2_climate_01",
        "title": "Le changement climatique",
        "level": "B2",
        "unit": "Environment",
        "theme": "Climate",
        "focus": "argument rhythm, longer phrasing",
        "grammar_focus": "exiger + noun phrase",
        "skills": ["reading aloud", "global issues"],
        "target_words": ["changement", "coordonnées", "internationale"],
        "liaison_targets": [],
        "teacher_tip": "Chunk the sentence into cause and response.",
        "text": "Le changement climatique exige des réponses coordonnées à l'échelle nationale et internationale."
    },
    {
        "id": "b2_citizenship_01",
        "title": "L’engagement citoyen",
        "level": "B2",
        "unit": "Civic life",
        "theme": "Democracy",
        "focus": "formal tone, connected discourse",
        "grammar_focus": "nominalization, abstract vocabulary",
        "skills": ["reading aloud", "civic discourse"],
        "target_words": ["participation", "démocratique", "institutions"],
        "liaison_targets": [],
        "teacher_tip": "Have learners emphasize the main institutional nouns.",
        "text": "La participation des citoyens à la vie démocratique renforce la stabilité des institutions."
    },
    {
        "id": "b2_health_02",
        "title": "L’accès à la santé",
        "level": "B2",
        "unit": "Public policy",
        "theme": "Public health",
        "focus": "clear articulation in abstract talk",
        "grammar_focus": "abstract subjects, present tense",
        "skills": ["reading aloud", "public policy vocabulary"],
        "target_words": ["équitable", "soins", "enjeu"],
        "liaison_targets": [],
        "teacher_tip": "Keep the sentence measured and formal.",
        "text": "L'accès équitable aux soins de santé demeure un enjeu central dans de nombreux pays."
    },
    {
        "id": "b2_identity_01",
        "title": "Les langues et l’identité",
        "level": "B2",
        "unit": "Language and identity",
        "theme": "Identity",
        "focus": "prosodic grouping, abstract vocabulary",
        "grammar_focus": "role of abstract nouns",
        "skills": ["reading aloud", "identity discourse"],
        "target_words": ["langue", "construction", "collective"],
        "liaison_targets": [],
        "teacher_tip": "Use phrasing to separate individual and collective dimensions.",
        "text": "La langue joue un rôle essentiel dans la construction de l'identité individuelle et collective."
    },
    {
        "id": "b2_study_abroad_01",
        "title": "Étudier à l’international",
        "level": "B2",
        "unit": "Education",
        "theme": "International study",
        "focus": "formal explanation, smooth transitions",
        "grammar_focus": "permettre de + infinitive",
        "skills": ["reading aloud", "educational discourse"],
        "target_words": ["international", "académiques", "interculturelles"],
        "liaison_targets": [],
        "teacher_tip": "Maintain a balanced rhythm across both halves of the sentence.",
        "text": "Étudier à l'international permet de développer des compétences académiques et interculturelles solides."
    },

    # =========================================================
    # C1 (10)
    # =========================================================
    {
        "id": "c1_academic_01",
        "title": "Discours académique",
        "level": "C1",
        "unit": "Academic French",
        "theme": "Academic",
        "focus": "formal fluency, precision",
        "grammar_focus": "abstract nominal structures",
        "skills": ["reading aloud", "academic pronunciation"],
        "target_words": ["recherche", "évidence", "sociolinguistiques"],
        "liaison_targets": ["les dynamiques"],
        "teacher_tip": "Prioritize prosodic grouping over speed.",
        "text": "Cette recherche met en évidence les dynamiques sociolinguistiques du discours."
    },
    {
        "id": "c1_diversity_01",
        "title": "La diversité linguistique",
        "level": "C1",
        "unit": "Linguistics",
        "theme": "Language policy",
        "focus": "abstract concepts, longer syntactic flow",
        "grammar_focus": "constituer, abstraction",
        "skills": ["reading aloud", "academic discourse"],
        "target_words": ["diversité", "richesse", "politiques"],
        "liaison_targets": [],
        "teacher_tip": "Encourage learners to articulate conceptual nouns clearly.",
        "text": "La diversité linguistique constitue une richesse culturelle, mais aussi un défi pour les politiques éducatives."
    },
    {
        "id": "c1_memory_01",
        "title": "La mémoire collective",
        "level": "C1",
        "unit": "History and society",
        "theme": "Memory",
        "focus": "prosodic phrasing in abstract discourse",
        "grammar_focus": "se construire, passive meaning",
        "skills": ["reading aloud", "historical discourse"],
        "target_words": ["mémoire", "récits", "pratiques"],
        "liaison_targets": [],
        "teacher_tip": "Group the final list into three balanced units.",
        "text": "La mémoire collective se construit à travers des récits, des symboles et des pratiques sociales partagées."
    },
    {
        "id": "c1_social_change_01",
        "title": "Les transformations sociales",
        "level": "C1",
        "unit": "Society",
        "theme": "Social change",
        "focus": "formal rhythm, lexical precision",
        "grammar_focus": "complex subjects and objects",
        "skills": ["reading aloud", "social analysis"],
        "target_words": ["transformations", "contemporaines", "institutions"],
        "liaison_targets": [],
        "teacher_tip": "Use a serious, measured tone appropriate for analysis.",
        "text": "Les transformations sociales contemporaines modifient profondément les rapports entre individus et institutions."
    },
    {
        "id": "c1_power_01",
        "title": "Langage et pouvoir",
        "level": "C1",
        "unit": "Political discourse",
        "theme": "Politics",
        "focus": "connected formal register",
        "grammar_focus": "ne... pas seulement, parallel structures",
        "skills": ["reading aloud", "political discourse"],
        "target_words": ["politique", "réalité", "construire"],
        "liaison_targets": [],
        "teacher_tip": "Highlight the contrast between description and construction.",
        "text": "Le langage politique ne se contente pas de décrire la réalité, il contribue aussi à la construire."
    },
    {
        "id": "c1_ethics_01",
        "title": "L’éthique du numérique",
        "level": "C1",
        "unit": "Technology and society",
        "theme": "Technology",
        "focus": "fluency in abstract reasoning",
        "grammar_focus": "impose + noun phrase",
        "skills": ["reading aloud", "ethical reflection"],
        "target_words": ["éthique", "collecte", "circulation"],
        "liaison_targets": [],
        "teacher_tip": "Keep the three noun phrases parallel and clear.",
        "text": "L'éthique du numérique impose une réflexion critique sur la collecte, l'usage et la circulation des données."
    },
    {
        "id": "c1_inequality_01",
        "title": "Les inégalités sociales",
        "level": "C1",
        "unit": "Social justice",
        "theme": "Inequality",
        "focus": "controlled phrasing, emphasis",
        "grammar_focus": "malgré, discourse contrast",
        "skills": ["reading aloud", "critical social discourse"],
        "target_words": ["inégalités", "institutionnels", "équité"],
        "liaison_targets": [],
        "teacher_tip": "Use a slightly stronger tone on the key contrastive words.",
        "text": "Les inégalités sociales persistent malgré les discours institutionnels en faveur de l'inclusion et de l'équité."
    },
    {
        "id": "c1_public_speech_01",
        "title": "La parole publique",
        "level": "C1",
        "unit": "Communication",
        "theme": "Public discourse",
        "focus": "discursive rhythm, formal tone",
        "grammar_focus": "causal clause with car",
        "skills": ["reading aloud", "public communication"],
        "target_words": ["responsabilité", "influence", "collectives"],
        "liaison_targets": [],
        "teacher_tip": "Keep the cause-and-effect structure audible.",
        "text": "La parole publique engage une responsabilité particulière, car elle influence les représentations collectives."
    },
    {
        "id": "c1_critical_education_01",
        "title": "L’éducation critique",
        "level": "C1",
        "unit": "Education and thought",
        "theme": "Education",
        "focus": "complex linking, intellectual register",
        "grammar_focus": "permettre à + noun + de + infinitive",
        "skills": ["reading aloud", "educational discourse"],
        "target_words": ["apprenants", "évidences", "dominants"],
        "liaison_targets": [],
        "teacher_tip": "Read once slowly for structure, then again for fluency.",
        "text": "Une éducation critique permet aux apprenants de remettre en question les évidences et les discours dominants."
    },
    {
        "id": "c1_globalization_01",
        "title": "La mondialisation culturelle",
        "level": "C1",
        "unit": "Culture",
        "theme": "Globalization",
        "focus": "long phrases, abstract lexical control",
        "grammar_focus": "tout en + gerund",
        "skills": ["reading aloud", "cultural analysis"],
        "target_words": ["mondialisation", "échanges", "identités"],
        "liaison_targets": [],
        "teacher_tip": "Help learners hear the two-part structure of the sentence.",
        "text": "La mondialisation culturelle favorise les échanges, tout en suscitant des tensions autour des identités locales."
    },

    # =========================================================
    # C2 (10)
    # =========================================================
    {
        "id": "c2_philosophy_01",
        "title": "Analyse philosophique",
        "level": "C2",
        "unit": "Advanced discourse",
        "theme": "Philosophy",
        "focus": "complex syntax, precision",
        "grammar_focus": "abstract clause structure",
        "skills": ["reading aloud", "advanced discourse"],
        "target_words": ["conscience", "critique", "réflexion", "langage"],
        "liaison_targets": [],
        "teacher_tip": "Read once slowly for structure, then again for natural flow.",
        "text": "La conscience critique se développe à travers une réflexion approfondie sur le langage."
    },
    {
        "id": "c2_real_01",
        "title": "Le statut du réel",
        "level": "C2",
        "unit": "Philosophy",
        "theme": "Epistemology",
        "focus": "abstract structure, precise articulation",
        "grammar_focus": "passive-like complex structures",
        "skills": ["reading aloud", "philosophical discourse"],
        "target_words": ["statut", "dissocié", "interprétatifs"],
        "liaison_targets": [],
        "teacher_tip": "Encourage very deliberate pacing and clear clause boundaries.",
        "text": "Le statut du réel ne peut être dissocié des cadres interprétatifs à travers lesquels il est appréhendé."
    },
    {
        "id": "c2_power_01",
        "title": "Pouvoir et subjectivité",
        "level": "C2",
        "unit": "Critical theory",
        "theme": "Theory",
        "focus": "dense conceptual language",
        "grammar_focus": "causal and instrumental phrasing",
        "skills": ["reading aloud", "theoretical discourse"],
        "target_words": ["mécanismes", "subjectivité", "normes"],
        "liaison_targets": [],
        "teacher_tip": "Keep the conceptual chain coherent and not overly rushed.",
        "text": "Les mécanismes de pouvoir façonnent la subjectivité en imposant des normes de perception et d'action."
    },
    {
        "id": "c2_hermeneutics_01",
        "title": "Herméneutique du discours",
        "level": "C2",
        "unit": "Theory",
        "theme": "Interpretation",
        "focus": "long abstract phrasing",
        "grammar_focus": "suppose une interrogation sur",
        "skills": ["reading aloud", "critical theory"],
        "target_words": ["herméneutique", "conditions", "production"],
        "liaison_targets": [],
        "teacher_tip": "Practice the sentence in two large semantic blocks.",
        "text": "Toute analyse herméneutique suppose une interrogation sur les conditions mêmes de production du sens."
    },
    {
        "id": "c2_modernity_01",
        "title": "Modernité et fragmentation",
        "level": "C2",
        "unit": "Philosophy",
        "theme": "Modernity",
        "focus": "high-level prosodic control",
        "grammar_focus": "se caractériser par",
        "skills": ["reading aloud", "conceptual explanation"],
        "target_words": ["modernité", "fragmentation", "légitimation"],
        "liaison_targets": [],
        "teacher_tip": "Keep the final abstract phrase tightly grouped.",
        "text": "La modernité se caractérise par une fragmentation des repères symboliques et des récits de légitimation."
    },
    {
        "id": "c2_truth_01",
        "title": "La vérité en débat",
        "level": "C2",
        "unit": "Epistemology",
        "theme": "Truth",
        "focus": "formal argument rhythm",
        "grammar_focus": "ne... jamais comme, mais comme",
        "skills": ["reading aloud", "philosophical argument"],
        "target_words": ["immédiate", "résultat", "discursive"],
        "liaison_targets": [],
        "teacher_tip": "Make the opposition structure clearly audible.",
        "text": "La vérité n'apparaît jamais comme une donnée immédiate, mais comme le résultat d'une construction discursive."
    },
    {
        "id": "c2_subject_language_01",
        "title": "Le sujet et la langue",
        "level": "C2",
        "unit": "Linguistic philosophy",
        "theme": "Language and subjectivity",
        "focus": "precision, complex phrasing",
        "grammar_focus": "puisque, reflexive structures",
        "skills": ["reading aloud", "advanced linguistic theory"],
        "target_words": ["sujet", "extérieur", "constitue", "exprime"],
        "liaison_targets": [],
        "teacher_tip": "Encourage precise reading of reflexive verbs and clause links.",
        "text": "Le sujet parlant n'est jamais extérieur à la langue, puisqu'il s'y constitue en même temps qu'il s'y exprime."
    },
    {
        "id": "c2_temporality_01",
        "title": "Temporalité et mémoire",
        "level": "C2",
        "unit": "Philosophy",
        "theme": "Time and memory",
        "focus": "abstract rhythm, long clause control",
        "grammar_focus": "se déployer dans",
        "skills": ["reading aloud", "philosophical abstraction"],
        "target_words": ["temporalité", "articulation", "anticipation"],
        "liaison_targets": [],
        "teacher_tip": "Keep the three-part conceptual list evenly paced.",
        "text": "La temporalité humaine se déploie dans l'articulation instable entre mémoire, expérience et anticipation."
    },
    {
        "id": "c2_interpretive_01",
        "title": "La condition interprétative",
        "level": "C2",
        "unit": "Theory",
        "theme": "Interpretation",
        "focus": "discursive density",
        "grammar_focus": "relative clauses, abstraction",
        "skills": ["reading aloud", "advanced theory"],
        "target_words": ["compréhension", "interprétative", "neutralisable"],
        "liaison_targets": [],
        "teacher_tip": "Take time to separate the main clause from the subordinate structure.",
        "text": "Toute compréhension du monde repose sur une condition interprétative qui n'est jamais totalement neutralisable."
    },
    {
        "id": "c2_existence_01",
        "title": "Langage et existence",
        "level": "C2",
        "unit": "Philosophy",
        "theme": "Existence",
        "focus": "very advanced connected speech",
        "grammar_focus": "ne... pas simplement ; parallel clauses",
        "skills": ["reading aloud", "high-level discourse"],
        "target_words": ["reflète", "élaboration", "symbolique"],
        "liaison_targets": [],
        "teacher_tip": "Use a measured, reflective tone and keep the clause contrast strong.",
        "text": "Le langage ne reflète pas simplement l'existence ; il participe à son élaboration symbolique et sociale."
    }
]

# -----------------------------
# Continue with the rest of your existing app logic below
# -----------------------------